- link: "project/nova-victoria-building-5"
  imagePath: asset/image/project/nova-victoria-building-5/main-nova-victoria-building.jpg
  imageList:
    - asset/image/project/nova-victoria-building-5/nova-victoria-building1.jpg
    - asset/image/project/nova-victoria-building-5/nova-victoria-building2.jpg
    - asset/image/project/nova-victoria-building-5/nova-victoria-building3.jpg

  title: Nova Victoria - Building 5 London
  descriptionList:
    - Internal mastic installation on Skirtings and Marble.

- link: "project/135-bishops-gate"
  imagePath: asset/image/project/135-bishops-gate/main-bishop.jpg
  imageList:
    - asset/image/project/135-bishops-gate/135-bishop-1.jpg
    - asset/image/project/135-bishops-gate/135-bishop-2.jpg
    - asset/image/project/135-bishops-gate/135-bishop-3.jpg
    - asset/image/project/135-bishops-gate/135-bishop-4.jpg
    - asset/image/project/135-bishops-gate/135-bishop-5.jpg
  title: 135 Bishops Gate London
  descriptionList:
    - In Development.
    - External mastic installation on Roofs, Terraces and Cladding.

- link: "project/undershaft"
  imagePath: asset/image/project/undershaft/main-1-Undershaft-4.jpg
  imageList:
    - asset/image/project/undershaft/undershaft-1.jpg
    - asset/image/project/undershaft/undershaft-2.jpg
    - asset/image/project/undershaft/undershaft-3.jpg
    - asset/image/project/undershaft/undershaft-4.jpg
  title: Undershaft London
  descriptionList:
    - External and internal mastic installation on Curtain Walling.

- link: "project/11-15-grosvenor-cresent"
  imagePath: asset/image/project/11-15-grosvenor-cresent-2/grosvenor-crescent-2.jpg
  title: 11-15 Grosvenor Cresent London
  imageList:
    - asset/image/project/11-15-grosvenor-cresent-2/grosvenor-crescent-3.jpg
    - asset/image/project/11-15-grosvenor-cresent-2/grosvenor-crescent-4.jpg
    - asset/image/project/11-15-grosvenor-cresent-2/grosvenor-crescent-5.jpg
    - asset/image/project/11-15-grosvenor-cresent-2/grosvenor-crescent-6.jpg
    - asset/image/project/11-15-grosvenor-cresent-2/grosvenor-crescent-7.jpg
  descriptionList:
    - External and internal mastic installation on Curtain Waling and Brick.

- link: "project/30-cannon-street"
  imagePath: asset/image/project/30-cannon-street/cannon-street-1.jpg
  title: 30 Cannon Street London
  imageList:
    - asset/image/project/30-cannon-street/cannon-street.jpg
    - asset/image/project/30-cannon-street/cannon-street-2.jpg
    - asset/image/project/30-cannon-street/cannon-street-3.jpg
    - asset/image/project/30-cannon-street/cannon-street-4.jpg
    - asset/image/project/30-cannon-street/cannon-street-5.jpg
    - asset/image/project/30-cannon-street/cannon-street-6.jpg
    - asset/image/project/30-cannon-street/cannon-street-7.jpg
  descriptionList:
    - External and internal mastic installation on Glazing.

- link: "project/american-school"
  imagePath: asset/image/project/american-school/main-american-school2.jpg
  imageList:
    - asset/image/project/american-school/american-school-1.jpg
    - asset/image/project/american-school/american-school-2.jpg
    - asset/image/project/american-school/american-school-3.jpg
    - asset/image/project/american-school/american-school-4.jpg
    - asset/image/project/american-school/american-school-5.jpg
  title: American School London
  descriptionList:
    - External and internal mastic installation on Curtain Walling and roof.
  
- link: "project/chelsea-barracks"
  imagePath: asset/image/project/chelsea-barracks/main-chelsea-barracks-2.jpg
  imageList:
    - asset/image/project/chelsea-barracks/chelsea-barracks-1.jpg
    - asset/image/project/chelsea-barracks/chelsea-barracks-3.jpg
    - asset/image/project/chelsea-barracks/chelsea-barracks-4.jpg
    - asset/image/project/chelsea-barracks/chelsea-barracks-5.jpg
    - asset/image/project/chelsea-barracks/chelsea-barracks-6.jpg
  title: Chelsea Barracks London
  descriptionList:
    - In Development.
    - Internal mastic installation on stairs  kitchens, bathrooms, swimming pools, powder rooms and steam rooms.

- link: "project/kensington-row"
  imagePath: asset/image/project/kensington-row/main-kensington-row.jpg
  imageList:
    - asset/image/project/kensington-row/kensington-row-1.jpg
    - asset/image/project/kensington-row/kensington-row-3.jpg
  title: Kensington Row London
  descriptionList:
    - External and internal mastic installation on Curtain Walling, Stone and Cladding.

- link: "project/lancon-house"
  imagePath: asset/image/project/lancon-house/main-lancon-3.jpg
  imageList:
    - asset/image/project/lancon-house/lancon-1.jpg
    - asset/image/project/lancon-house/lancon-2.jpg
  title: Lancon House London
  descriptionList:
    - External and internal mastic installation on Curtain Walling and Cladding.

- link: "project/lillie-square"
  imagePath: asset/image/project/lillie-square/main-lillie-square-3.jpg
  imageList:
    - asset/image/project/lillie-square/lillie-square-1.jpg
    - asset/image/project/lillie-square/lillie-square-2.jpg
    - asset/image/project/lillie-square/lillie-square.jpg
  title: Lillie Square London
  descriptionList:
    - External mastic installation on Curtain Walling and Coppings.

- link: "project/one-tower-bridge-building-5"
  imagePath: asset/image/project/one-tower-bridge-building-5/main-one-tower-bridge-london.jpg
  imageList:
    - asset/image/project/one-tower-bridge-building-5/one-tower-1.jpg
    - asset/image/project/one-tower-bridge-building-5/one-tower-2.jpg
    - asset/image/project/one-tower-bridge-building-5/one-tower-3.jpg
    - asset/image/project/one-tower-bridge-building-5/one-tower-4.jpg
  title: One Tower Bridge Building 5 London
  descriptionList:
    - External and internal mastic installation on curtain walling.

- link: "project/one-finsbury-circus"
  imagePath: asset/image/project/one-finsbury-circus/main-roofs-6-finsbury.jpg
  imageList:
    - asset/image/project/one-finsbury-circus/finsbury-circus-1.jpg
    - asset/image/project/one-finsbury-circus/finsbury-circus-2.jpg
  title: One Finsbury Circus London
  descriptionList:
    - External mastic installation on roof.

- link: "project/river-walk"
  imagePath: asset/image/project/river-walk/river-walk-3.jpg
  imageList:
    - asset/image/project/river-walk/river-walk-1.jpg
  title: River Walk London
  descriptionList:
    - External mastic installation on Curtain Walling.

- link: "project/triangle-cambridge"
  imagePath: asset/image/project/triangle-cambridge/main-triangle-4.jpg
  imageList:
    - asset/image/project/triangle-cambridge/image3.jpg
    - asset/image/project/triangle-cambridge/triangle-2.jpeg
  title: Triangle Cambridge
  descriptionList:
    - External mastic installation on Stone and Cladding.

- link: "project/tottenham-court-road"
  imagePath: asset/image/project/tottenham-court-road/tottenham-1.jpg
  imageList:
    - asset/image/project/tottenham-court-road/tottenham-2.jpg
    - asset/image/project/tottenham-court-road/tottenham-3.jpg
  title: Tottenham Court Road London
  descriptionList:
    - External mastic installation on Curtain Walling.

- link: "project/1-harman-boulevard-manchester"
  imagePath: asset/image/project/1-harman-boulevard-manchester/main-harman-boulevard.jpg
  title: 1 Harman Boulevard Manchester
  imageList:
    - asset/image/project/1-harman-boulevard-manchester/harman-boulevard-1.jpg
    - asset/image/project/1-harman-boulevard-manchester/harman-boulevard-2.jpg
    - asset/image/project/1-harman-boulevard-manchester/harman-boulevard-3.jpg
  descriptionList:
    - External	mastic installation on Canopy.

- link: "project/cathedral-lane-shopping-centre-coventry"
  imagePath: asset/image/project/cathedral-lane-shopping-centre-coventry/main-coventry.jpg
  imageList:
    - asset/image/project/cathedral-lane-shopping-centre-coventry/coventry1.jpg
  title: Cathedral Lane Shopping Centre Coventry
  descriptionList:
    - External mastic installation on Roof.

- link: "project/thomas-more"
  imagePath: asset/image/project/thomas-more/main-thomas-more3.jpg
  imageList:
    - asset/image/project/thomas-more/thomas-more.jpg
    - asset/image/project/thomas-more/thomas-more1.jpg
    - asset/image/project/thomas-more/thomas-more2.jpg
  title: Thomas More London
  descriptionList:
    - External and internal mastic installation on Cladding and Stone.

- link: "project/riverwalk-shopping"
  imagePath: asset/image/project/riverwalk-shopping/riverwalk-shopping-main.jpg
  imageList:
    - asset/image/project/riverwalk-shopping/riverwalk-shopping-1.jpg
    - asset/image/project/riverwalk-shopping/riverwalk-shopping-2.jpg
    - asset/image/project/riverwalk-shopping/riverwalk-shopping-3.jpg
    - asset/image/project/riverwalk-shopping/riverwalk-shopping-4.jpg
    - asset/image/project/riverwalk-shopping/riverwalk-shopping-5.jpg
    - asset/image/project/riverwalk-shopping/riverwalk-shopping-6.jpg
    - asset/image/project/riverwalk-shopping/riverwalk-shopping-7.jpg
  title: Riverwalk shopping centre - Hemel Hampstead
  descriptionList:
    - External mastic installation on aluminium panels.




